analyzer:
  exclude:
    - "flutter/**"
    - "third_party/**"
    - "engine/**"
    - "dev/**"
    - "packages/**"
    - "examples/**"
    - "docs/**"
    - "build/**"
    - "flutter_application_1/**"
